### ISSUE TITLE
global.loadData is not a function

### ISSUE THREAD

**Issue by daiyy2009** [quickappcn/quickapp-demo-quality#5]
Error: global.loadData is not a function,
at Vm.onShow

**Comment by LeeeeeeM** [comment]
> Error: global.loadData is not a function,
> at Vm.onShow
你手动安装下hap-toolkit@0.6.9试试，记得删除掉package-lock.json和node_modules

**Comment by diydyq** [comment]
使用上面最新的hap-toolkit版本是没有的；如果还遇到这个问题，请再reopen；

**Comment by droplet-js** [comment]
这个问题依然存在 [issues#11](https://github.com/quickappcn/quickapp-demo-quality/issues/11)
