### ISSUE TITLE
'NODE_TEST' 不是内部或外部命令，也不是可运行的程序

### ISSUE THREAD

**Issue by daiyy2009** [quickappcn/quickapp-demo-quality#7]
执行npm run build:test是报'NODE_TEST' 不是内部或外部命令，也不是可运行的程序

**Comment by diydyq** [comment]
抱歉，NODE_TEST在后面的toolkit里移除了，您如果需要的话，可以自己通过增加webpack配置的形式进行定义；
官方文档晚点更新增加quickapp.config.js的描述；
样例的示例，可以参考这个Github的说明：https://github.com/quickappcn/hap-toolkit-usage/tree/master/examples/project-config-simple；
